### ISSUE TITLE
sass:dist fails - spawn sass ENOENT Use --force to continue.

### ISSUE THREAD

**Issue by jsguy** [skounis/supermodular#45]
For anyone else getting this issue, I was seeing the following issue when trying to build for the first time:

```
Warning: Running "sass:dist" (sass) task
Warning: spawn sass ENOENT Use --force to continue.

Aborted due to warnings.
```

The solution is to re-install compass on Yosemite by running:

``` bash
xcode-select --install
sudo gem update --system
sudo gem install compass
```

Ref: http://stackoverflow.com/a/26435480

**Comment by jsguy** [comment]
Simply added issue in case anyone else has the same problem, so closing now.

**Comment by NicholasPedroso** [comment]
In case you get this error: "You don't have write permissions into the /usr/bin directory”
just run ```sudo gem install compass -n /usr/local/bin```

and voilà

**Comment by Viscore** [comment]
> In case you get this error: "You don't have write permissions into the /usr/bin directory”
> just run `sudo gem install compass -n /usr/local/bin`
> 
> and voilà

Worked for me!

**Comment by clagosarias** [comment]
Just to let anyone know... this happened with macOS Catalina again.
Running `sudo gem install compass -n /usr/local/bin` solved my whole entire life crisis. Big thanks <3
